### ISSUE TITLE
Table debugging can result in failure due to multiple result file creation attempts

### ISSUE THREAD

**Issue by drmacro** [dita4publishers/org.dita4publishers.dita2indesign#7]

**Comment by drmacro** [comment]
See xsl/calstbl2IcmlImpl.xsl, Line: 351, Col: 351

**Comment by peisenberg** [comment]
Hi Eliot. 
Can you tell me where this item stands in your backlog. Trying to understand how soon a fix might become available for testing.
Paul

**Comment by peisenberg** [comment]
Many thanks Eliot!
